<a href="https://colab.research.google.com/github/arturgmrs/integraschoolpython/blob/master/Aula_4_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introdução à Programação Python - Integra School 2020.1
Carlos Artur Guimarães
Pacote Numpy-Python

## Adaptado: Disciplina: Análise da Aprendizagem UFRN(ITE 0021)
PPGTI - UFRN 2019-2

In [0]:
# Importando o comando numpy
import numpy
import numpy as np

In [0]:
#Diferença entre lista e Array
python_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print ((python_list) * 2)

numpy_array = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9])
print ((numpy_array) *2)

In [0]:
#Para analisar o tamanho da array
numpy_array = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9])
print (numpy_array.size)


In [0]:
# Identificar o tamanho de uma matriz
numpy_matrix = np.array ([(1, 2, 3, 4), (5, 6, 7, 8)])
print (numpy_matrix.shape)

(2, 4)


In [0]:
# Alteração de uma matriz
numpy_matrix = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
numpy_matrix = numpy_matrix.reshape(4, 2)
print(numpy_matrix)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [0]:
#Extração de vários valores no array
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array[0:8])

[1 2 3 4 5 6 7 8]


In [0]:
#Alterando a ordem dos valores no array
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array[::-1])

[9 8 7 6 5 4 3 2 1]


In [0]:
#Max, min e Soma no array
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array.max())
9
print(numpy_array.min())
1
print(numpy_array.sum())

9
1
45


In [0]:
# Mean, mediana, variância e derivada
 
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array.mean())
print (np.median (numpy_array))
print(numpy_array.median()) #não funcionu
print(numpy_array.var())
print(numpy_array.std())

5.0
5.0
6.666666666666667
2.581988897471611


In [0]:
#Fazendo operações por eixos 
print(numpy_matrix)
print(numpy_matrix.sum(axis = 0))
print(numpy_matrix.sum(axis = 1))
print(numpy_matrix.sum(axis = None))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[16 20]
[ 3  7 11 15]
36


In [0]:
#Concatenando matrizes
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])
print(np.concatenate((array_1, array_2, array_3)))    
array_4 = np.array([[1,2,3],[0,0,0]])
array_5 = np.array([[0,0,0],[7,8,9]])
print(np.concatenate((array_4, array_5), axis = 1))   

[1 2 3 4 5 6 7 8 9]
[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


In [0]:
#imprimindo array com zeros e uns
print(np.zeros((1,2)))                   
print(np.zeros((1,2), dtype = np.int)) 
print(np.ones((1,2)))                   
print(np.ones((1,2), dtype = np.int))

[[0. 0.]]
[[0 0]]
[[1. 1.]]
[[1 1]]


In [0]:
#imprimindo matrizes de identidade
print(np.identity(3))
#imprimindo matriz de 3x3
print(np.eye(8, 7, k = 1))    
#imprimindo matriz de 8x7, com primeira diagnal superior denotada com k =1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [0]:
# Multiplicando matrizes
array_6 = np.array([ 1, 2])
array_7 = np.array([3, 4 ])
print(np.dot(array_6, array_7))    
print(np.cross(array_6, array_7))   

#[ 1, 2 ] x [ 3, 4 ] = 3 + 8

11
-2


In [0]:
import numpy as np

A = np.array ([2, 3])
B = np.array ([1, 2])

output = np.cross (A, B)

print (output)

1


In [0]:
import numpy as np
A = np.array ([2, 7, 4])
B = np.array ([3, 9, 8])

output = np.cross (A,B)

print (output)

[20 -4 -3]
